---
# @meta description: >
# Requires all core infrastructure components to be deployed and configured
#
# - Configure default intentions for services
# @end

- ansible.builtin.import_tasks: ../../common-tasks/consul_login/consul_login.yaml

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    CONSUL_HTTP_ADDR: "{{ consul.url }}"
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"
  block:
    - name: Ensure working directory
      ansible.builtin.file:
        path: /tmp/services/consul_services
        state: directory

    - ansible.builtin.set_fact:
        gateway_services: "{{ services.backend | selectattr('use_ingress_gateway', 'true') }}"
        intentions:
          - postgres
          - nats
          - zitadel
          - commerce-api

    - name: Copy intention configurations to working directory
      ansible.builtin.copy:
        src: "{{ item }}_intention.json"
        dest: "/tmp/services/consul_services/{{ item }}_intention.json"
      with_items: "{{ intentions }}"

    - name: Create consul intentions
      ansible.builtin.command: >-
        consul config write /tmp/services/consul_services/{{ item }}_intention.json
      with_items: "{{ intentions }}"
