---
# @meta description: >
# - Install [Nomad](https://developer.hashicorp.com/nomad)
# - Install [CNI plugin](https://github.com/containernetworking/cni)
# - Install [Docker](https://docs.docker.com/)
# @end

- ansible.builtin.import_tasks: ../../common-tasks/hashicorp_repository/hashicorp_repository.yaml

- name: Install nomad package
  ansible.builtin.apt:
    name: nomad
    state: latest
    update_cache: true

- name: Ensure nomad service is enabled
  ansible.builtin.service:
    name: nomad
    state: started
    enabled: true

- name: Ensure CNI plugin dir exists
  ansible.builtin.file:
    path: "{{ nomad.cni_plugin_dir }}/"
    state: directory

- name: Download and untar CNI plugin
  ansible.builtin.unarchive:
    src: "{{ nomad.cni_plugin_url }}"
    dest: "{{ nomad.cni_plugin_dir }}"
    remote_src: true

- name: Copy iptables bridge config
  ansible.builtin.copy:
    src: "20-bridge.conf.j2"
    dest: "/etc/sysctl.d/20-bridge.conf"
    owner: root
    group: root
    mode: 0644

- name: Ensure nomad plugin dir exists
  ansible.builtin.file:
    path: "{{ nomad.data_dir }}/plugins/"
    state: directory
    owner: nomad
    group: nomad
    mode: 0775

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker repo to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - Docker Restarted
    - Nomad Restarted

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add admin and nomad to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - admin
    - nomad
