---
# @meta description: >
# Requires all core infrastructure components to be deployed and configured
#
# - Configure Nginx as public facing proxy for service backends
# @end

- ansible.builtin.import_tasks: ../../common-tasks/ufw/ufw.yaml

- name: Configure firewall allow http 443
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- ansible.builtin.set_fact:
    gateway_services: "{{ services.backend | selectattr('use_ingress_gateway', 'true') }}"
    frontend_services: "{{ services.frontend }}"

- name: Copy services gateway nginx config template
  ansible.builtin.template:
    src: services_gateway.conf.tpl.j2
    dest: "{{ consul_template.data_dir }}/services_gateway.conf.tpl"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted

- name: Copy fronted gateway nginx config template
  ansible.builtin.template:
    src: frontend_gateway_conf.tpl.j2
    dest: "{{ consul_template.data_dir }}/frontend_gateway.conf.tpl"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted

- name: Copy services gateway consul-template config
  ansible.builtin.template:
    src: services_gateway_conf_ctmpl.hcl.j2
    dest: "{{ consul_template.config_dir }}/services_gateway_conf_ctmpl.hcl"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted

- ansible.builtin.file:
    path: /etc/nginx/conf.d/frontend_gateway_conf
    state: absent
