---
# @meta description: >
# Requires [Vault](../../vault/) to be run in order to use PKI
# - Get new SSL certificates from vault pki and update consul agents
# @end
#

- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  block:
    - name: Get server certificates
      ansible.builtin.command: |
        vault write -format=json \
          pki-int/consul/issue/consul-{{ data_center }} \
          common_name=server.{{ data_center }}.consul \
          ttl=720h
      register: server_certificates_out

- name: Save CA
  ansible.builtin.copy:
    content: "{{ server_certificates_out.stdout | from_json | community.general.json_query('data.issuing_ca') }}"
    dest: "{{ consul.certs_dir }}/consul-agent-ca.pem"
  notify: Consul Reloaded

- name: Save certificate
  ansible.builtin.copy:
    content: "{{ server_certificates_out.stdout | from_json | community.general.json_query('data.certificate') }}"
    dest: "{{ consul.certs_dir }}/{{ data_center }}-server-{{ consul.domain }}.pem"
  when: inventory_hostname in groups.consul_servers
  notify: Consul Reloaded

- name: Save certificate key
  ansible.builtin.copy:
    content: "{{ server_certificates_out.stdout | from_json | community.general.json_query('data.private_key') }}"
    dest: "{{ consul.certs_dir }}/{{ data_center }}-server-{{ consul.domain }}-key.pem"
  when: inventory_hostname in groups.consul_servers
  notify: Consul Reloaded

- name: Copy server tls configurations
  ansible.builtin.template:
    src: server.tls.hcl.j2
    dest: "{{ consul.config_dir }}/server.tls.hcl"
    owner: consul
    group: consul
    mode: 0664
  when: inventory_hostname in groups.consul_servers
  notify: Consul Reloaded

- name: Copy client tls configurations
  ansible.builtin.template:
    src: client.tls.hcl.j2
    dest: "{{ consul.config_dir }}/client.tls.hcl"
    owner: consul
    group: consul
    mode: 0664
  when: inventory_hostname in groups.consul_clients
  notify: Consul Reloaded
