---
# @meta description: >
# Requires all core infrastructure components to be deployed and configured
#
# - Create Vault user for each service
# @end

- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  block:
    - name: Ensure working directory exists
      ansible.builtin.file:
        path: /tmp/services/vault_serivces/
        state: directory

    - name: Copy frontend service roles to working directory
      ansible.builtin.template:
        src: frontend-service.policy.hcl.j2
        dest: /tmp/services/vault_serivces/service-{{ item.name }}.hcl
      with_items: "{{ services.frontend }}"

    - name: Create frontend service roles on vault
      ansible.builtin.command: >-
        vault policy write service-{{ item.name }}
          /tmp/services/vault_serivces/service-{{ item.name }}.hcl
      with_items: "{{ services.frontend }}"

    - name: Copy backend service roles to working directory
      ansible.builtin.template:
        src: backend-service.policy.hcl.j2
        dest: /tmp/services/vault_serivces/service-{{ item.name }}.hcl
      with_items: "{{ services.backend }}"

    - name: Create backend service roles on vault
      ansible.builtin.command: >-
        vault policy write service-{{ item.name }}
          /tmp/services/vault_serivces/service-{{ item.name }}.hcl
      with_items: "{{ services.backend }}"
