---
all:
  vars:
    services:
      github_service_deployer_password_key: DEV_SERVICE_DEPLOYER_PASSWORD
      frontend:
        - name: project-frontend
          url: sited1.de
          custom_origin: false
        - name: dashboard-frontend
          url: dashboard.sited1.de
          custom_origin: false
        - name: websites-frontend
          url: "*.sited1.de"
          custom_origin: false
      databases:
        - name: zitadel
          user: zitadel_user
        - name: websites
          user: websites_user
        - name: commerce_v2
          user: commerce_v2_user
      backend:
        - name: websites
        - name: commerce_v2
