---
# @meta description: >
# Prepare Vault deployment
# - Create self signed SSL certificate
# @end

- name: Generate new certificates
  run_once: true
  delegate_to: localhost
  when: secrets.vault.ssl_ca_certificate_key == "" or secrets.vault.ssl_ca_certificate == "" or secrets.vault.ssl_certificate_key == "" or secrets.vault.ssl_certificate == ""
  block:
    - name: Ensure working directory
      ansible.builtin.file:
        path: "/tmp/vault/certs"
        state: directory

    - name: Generate CA certificate key
      ansible.builtin.command: |
        openssl ecparam \
          -name prime256v1 \
          -genkey \
          -noout \
          -out /tmp/vault/certs/ca.key

    - name: Generate CA certificate
      ansible.builtin.command: |
        openssl req \
          -x509 \
          -new \
          -key /tmp/vault/certs/ca.key \
          -out /tmp/vault/certs/ca.crt \
          -sha256 \
          -days 3650 \
          -nodes \
          -subj "/CN=Vault"

    - name: Generate key for vault certificate
      ansible.builtin.command: |
        openssl ecparam \
          -name prime256v1 \
          -genkey \
          -noout \
          -out /tmp/vault/certs/client.key

    - name: Generate vault certificate request
      ansible.builtin.command: |
        openssl req \
          -new \
          -key /tmp/vault/certs/client.key \
          -out /tmp/vault/certs/client.csr \
          -subj "/CN=Vault"

    - name: Copy cert configuration to working dir
      ansible.builtin.template:
        src: cert.conf.j2
        dest: /tmp/vault/certs/cert.conf

    - name: Sign vault certificate
      ansible.builtin.command: |
        openssl x509 -req \
          -in /tmp/vault/certs/client.csr \
          -CA /tmp/vault/certs/ca.crt \
          -CAkey /tmp/vault/certs/ca.key \
          -CAcreateserial \
          -out /tmp/vault/certs/client.crt \
          -days 365 \
          -sha256 \
          -extfile /tmp/vault/certs/cert.conf

    - set_fact:
        ssl_ca_certificate: "{{ lookup('ansible.builtin.file', '/tmp/vault/certs/ca.crt').replace('\n', '\\n') }}"
        ssl_ca_certificate_key: "{{ lookup('ansible.builtin.file', '/tmp/vault/certs/ca.key').replace('\n', '\\n') }}"
        ssl_certificate: "{{ lookup('ansible.builtin.file', '/tmp/vault/certs/client.crt').replace('\n', '\\n') }}"
        ssl_certificate_key: "{{ lookup('ansible.builtin.file', '/tmp/vault/certs/client.key').replace('\n', '\\n') }}"

    - name: Manually add the following values to secrets file and restart playbook.
      ansible.builtin.pause:
        prompt: |
          secrets:
            vault:
              ssl_ca_certificate: '{{ ssl_ca_certificate }}'
              ssl_ca_certificate_key: '{{ ssl_ca_certificate_key }}'
              ssl_certificate: '{{ ssl_certificate }}'
              ssl_certificate_key: '{{ ssl_certificate_key }}'

- fail:
  when: secrets.vault.ssl_ca_certificate_key == "" or secrets.vault.ssl_ca_certificate == "" or secrets.vault.ssl_certificate_key == "" or secrets.vault.ssl_certificate == ""
